export const START_FETCH_TODOS = 'START_FETCH_TODOS';
export const FINISH_FETCH_TODOS = 'FINISH_FETCH_TODOS';
export const ERROR_FETCH_TODOS = 'ERROR_FETCH_TODOS';
export const ADD_TODO = 'ADD_TODO';
export const CHANGE_INPUT_DATA = 'CHANGE_INPUT_DATA';
